# PR Verification pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - features/*

stages:
- stage: i386_verification
  displayName: Build and verify i386 architecutre
  pool: vali-builders
  jobs:
    - job: compile
      timeoutInMinutes: 10
      steps:
        - bash: make
          env:
            VALI_ARCH: i386
- stage: amd64_verification
  displayName: Build and verify amd64 architecutre
  pool: vali-builders
  jobs:
    - job: compile
      timeoutInMinutes: 10
      steps:
        - bash: make
          env:
            VALI_ARCH: amd64