# Build and package pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: architecture
  type: string
  default: 'amd64'

stages:
- stage: build
  displayName: Build kernel and drivers - ${{ parameters.architecture }}
  pool: vali-builders
  jobs:
    - job: compile
      timeoutInMinutes: 10
      steps:
        - bash: make build
          env:
            VALI_ARCH: ${{ parameters.architecture }}
- stage: create_release
  displayName: Create release package
  dependsOn: build
  pool: vali-builders
  jobs:
    - job: package
      timeoutInMinutes: 10
      steps:
        - bash: make package_os
          env:
            VALI_ARCH: ${{ parameters.architecture }}
        - bash: make package_sdk
          env:
            VALI_ARCH: ${{ parameters.architecture }}
        - bash: make package_ddk
          env:
            VALI_ARCH: ${{ parameters.architecture }}
    - job: publish
      steps:
        - task: PublishBuildArtifacts@1
          displayName: Publish
          inputs:
            PathtoPublish: 'packages/'
            ArtifactName: 'release'
            publishLocation: 'Container'
