name: Vali AMD64 Nightly Image CI

on:
  # Nightly builds
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Download vali applications
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: nightly-amd64.yml
        workflow_conclusion: success
        branch: master
        repo: Meulengracht/vali-userspace
        check_artifacts: true
        path: ${{ github.workspace }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        build-args: ARCH=amd64
        file: nightly.Dockerfile
        target: artifact
        outputs: type=local,dest=.
    - uses: actions/upload-artifact@v2
      with:
        name: vali-nightly-amd64
        path: ./vali-nightly.tar.gz
