name: Vali AMD64 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Building image
      run: docker build --build-arg ARCH=amd64 . --file Dockerfile --tag vali-amd64:$(date +%s)
