name: Vali I386 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build and push
      uses: docker/build-push-action@v1.1.0
      with:
        build_args: ARCH=i386
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: fadekraft
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        # Docker repository to tag the image with
        repository: valios/os-base-i386
        tags: latest
